### ISSUE TITLE
Support for dns.he.net

### ISSUE THREAD

**Issue by uberushaximus** [nickbabcock/dness#266]
https://dns.he.net is a well known vendor that provides free DNS hosting.

Documentation is their service is available [here][1]

An existing rustlang implementation is additionally available [here][2]

Registration should be free and available for anyone to test.

[1]: https://dns.he.net/docs.html

[2]: https://github.com/ben-zen/ddns-updater

**Comment by nickbabcock** [comment]
Yes this is something that seems reasonable to add within the next few weeks.
