### ISSUE TITLE
Support noip.com

### ISSUE THREAD

**Issue by mlan** [nickbabcock/dness#274]
Please consider adding support for [No-IP](https://www.noip.com/) who offer free DDNS service with 30 million users.

They use an open format, based on  HTTP requests, also deployed by other service providers. The API is described here: [Request Method](https://www.noip.com/integrate/request).

**Comment by nickbabcock** [comment]
This looks quite similar to namecheap's api, so I this should be implemented within a few weeks.

**Comment by mlan** [comment]
Works perfectly for my system.

Thank you! 😊
